# -*- coding: utf-8 -*-
"""CNNprac.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gr2-evWSyUM_aAwgPKQ7DDP6_y-HeV-V
"""

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.datasets import cifar10
from tensorflow.keras.layers import Flatten,Dense,Conv2D,MaxPooling2D,Activation,Dropout
(xtrain,ytrain),(xtest,ytest)=cifar10.load_data()
# xtrain.shape
# import glob  // this is used to upload an array of image as datasets
# import cv2
# import numpy as np

# data = []
# for i in glob.glob('path/to/my/data/**/*.png', recursive=True):
#     data.append(cv2.imread(i))

# data = np.stack(data)

# import cv2
# data=cv2.imread('cat.1.jpg')
# import matplotlib.pyplot as plt
# plt.imshow(data)
# #dim=(28,28)
# #data=cv2.resize(data,dim,interpolation = cv2.INTER_AREA)
# #plt.imshow(data)
# #prac=np.asarray(data)
# #print(prac.shape)
xtrain.shape

#import pickle
#pickle_in=open('X.pickle','rb')
#X=pickle.load(pickle_in)

#pickle_in=open('Y.pickle','rb')
#Y=pickle.load(pickle_in)

X=tf.keras.utils.normalize(xtrain)
model=Sequential()

model.add(Conv2D(256,(3,3),input_shape=X.shape[1:]))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2,2)))

model.add(Conv2D(256,(3,3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2,2)))

model.add(Flatten())

model.add(Dense(64))

model.add(Dense(1))
model.add(Activation('sigmoid'))


model.compile(loss='binary_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])

model.fit(X, ytrain, batch_size=32,epochs=3, validation_split=0.3)
